# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
